# Generated by Django 4.1 on 2022-08-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tempImagesStorage')),
            ],
        ),
        migrations.AddField(
            model_name='manga',
            name='images',
            field=models.ManyToManyField(to='mangaApp.image'),
        ),
    ]
