# Generated by Django 4.1 on 2022-08-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0015_alter_chapter_manganame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangapackage',
            name='mangaName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaPackage', to='mangaApp.manga'),
        ),
    ]
