# Generated by Django 4.1 on 2022-11-08 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0020_manga_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mangas', models.ManyToManyField(blank=True, to='mangaApp.manga')),
            ],
        ),
    ]
