# Generated by Django 4.1 on 2022-11-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0024_rename_bannerimage_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritemanga',
            name='mangas',
            field=models.ManyToManyField(blank=True, related_name='favourMangas', to='mangaApp.manga'),
        ),
    ]
