# Generated by Django 4.1 on 2022-11-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0027_mangareadinghistory_readingstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayViews', to='mangaApp.manga')),
            ],
        ),
    ]
