# Generated by Django 4.1 on 2022-11-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0029_alter_dayviews_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayviews',
            old_name='day',
            new_name='currentDay',
        ),
    ]
