# Generated by Django 4.1 on 2024-05-08 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaApp', '0032_rename_likes_manga_favourites_alter_manga_totalstars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='mangas',
            field=models.ManyToManyField(blank=True, related_name='categories', to='mangaApp.manga'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mangas', models.ManyToManyField(blank=True, related_name='album', to='mangaApp.manga')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
