# Generated by Django 4.1 on 2024-05-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0033_alter_category_mangas_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='mangas',
            new_name='mangaList',
        ),
    ]
