# Generated by Django 5.0.1 on 2025-02-19 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0038_mangauserrating_mangauserrating_user_manga_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangauserrating',
            name='manga',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userRatings', to='mangaApp.manga'),
        ),
        migrations.AlterField(
            model_name='mangauserrating',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaRatings', to=settings.AUTH_USER_MODEL),
        ),
    ]
