# Generated by Django 4.1 on 2022-08-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0003_remove_image_file_remove_manga_images_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='images',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
