# Generated by Django 4.1 on 2022-08-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0006_rename_parent_chapter_manganame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='images',
            new_name='chapterZipData',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangaApp.chapter')),
            ],
        ),
    ]
