# Generated by Django 4.1 on 2022-08-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0007_rename_images_chapter_chapterzipdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='chapter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mangaApp.chapter'),
        ),
    ]
