# Generated by Django 4.1 on 2022-08-23 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0008_alter_image_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mangaApp.chapter'),
        ),
    ]
