# Generated by Django 4.1 on 2022-08-23 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0011_mangapackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='mangaName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='mangaApp.manga'),
        ),
        migrations.AlterField(
            model_name='image',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='mangaApp.chapter'),
        ),
        migrations.AlterField(
            model_name='mangapackage',
            name='mangaName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mangaPackage', to='mangaApp.manga'),
        ),
    ]
