# Generated by Django 4.1 on 2022-08-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0012_alter_chapter_manganame_alter_image_chapter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Picture',
        ),
    ]
