# Generated by Django 4.1 on 2022-08-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0013_rename_image_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('index',)},
        ),
    ]
