# Generated by Django 4.1 on 2022-08-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0014_alter_chapter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='mangaName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='mangaApp.manga'),
        ),
    ]
