# Generated by Django 4.1 on 2022-09-12 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaApp', '0016_alter_mangapackage_manganame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='mangaName',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter', to='mangaApp.manga'),
        ),
        migrations.AlterField(
            model_name='mangapackage',
            name='mangaName',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaPackage', to='mangaApp.manga'),
        ),
        migrations.CreateModel(
            name='FavouriteManga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mangas', models.ManyToManyField(to='mangaApp.manga')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
