# Generated by Django 4.1 on 2022-09-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0017_alter_chapter_manganame_alter_mangapackage_manganame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritemanga',
            name='mangas',
            field=models.ManyToManyField(blank=True, to='mangaApp.manga'),
        ),
    ]
