# Generated by Django 4.1 on 2022-09-12 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaApp', '0018_alter_favouritemanga_mangas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritemanga',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourMangas', to=settings.AUTH_USER_MODEL),
        ),
    ]
