# Generated by Django 4.1 on 2022-09-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0019_alter_favouritemanga_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
