# Generated by Django 4.1 on 2022-11-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0021_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
