# Generated by Django 4.1 on 2022-11-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0025_alter_favouritemanga_mangas'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='totalStars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='totalVotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
