# Generated by Django 4.1 on 2022-11-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0028_dayviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayviews',
            name='day',
            field=models.DateField(auto_now_add=True),
        ),
    ]
