# Generated by Django 4.1 on 2022-11-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0030_rename_day_dayviews_currentday'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mangareadinghistory',
            name='watchedChapters',
            field=models.ManyToManyField(blank=True, related_name='readingHistory', to='mangaApp.chapter'),
        ),
    ]
