# Generated by Django 4.1 on 2023-01-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0031_chapter_title_mangareadinghistory_watchedchapters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='likes',
            new_name='favourites',
        ),
        migrations.AlterField(
            model_name='manga',
            name='totalStars',
            field=models.FloatField(default=0),
        ),
    ]
