# Generated by Django 4.1 on 2024-05-08 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mangaApp', '0034_rename_mangas_album_mangalist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='mangaList',
            field=models.ManyToManyField(blank=True, related_name='albums', to='mangaApp.manga'),
        ),
        migrations.AlterField(
            model_name='album',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
