# Generated by Django 5.0.1 on 2025-02-19 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaApp', '0037_alter_album_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('manga', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userRating', to='mangaApp.manga')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mangaRating', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='mangauserrating',
            constraint=models.UniqueConstraint(fields=('user', 'manga'), name='user_manga_unique'),
        ),
    ]
